kytos-ng/of_core

flow.py
tests/unit/test_flow.py
v0x01/flow.py
v0x04/flow.py

This pull request implements #14.
Description of the change
----------------------------
This PR implements high-level classes for Instructions in OpenFlow 1.3. To do so, the generic flow class does not have an `actions` attribute anymore. The `actions` attribute now only exists in OF 1.0 Flow class. OF 1.3 flow class has a `instructions` attribute, a list
of Instructions.
Base classes for instructions are implemented in base flow file, and the specific classes are implemented in OF 1.3 flow file.
For OF 1.3, `Flow.from_dict` method still support a dict with actions outside instructions, but `Flow.as_dict` always return a dict with actions inside a instruction.
Testing
--------
Some tests had to be changed to reflact the new behavior with `actions`.
New tests were also written.
Release …

Instructions

---

requirements/dev.in
requirements/dev.txt

This PR fixes #19 
Description of the change
-----------------------------
The requirement files were changes to replate `github.com/kytos` with `github.com/kytos-ng`.
Release notes
---------------
N/A

Replace kytos with kytos-ng in the requirements file

---

tests/unit/v0x04/test_utils.py
v0x01/utils.py
v0x04/utils.py

This PR fixes #17 
Description of the change
-----------------------------
The change enables of_core to use the recently created function `Switch. update_or_create_interface()` instead of creating/updating the Interfaces directly. Using the `Switch.update_or_create_interface()` avoids race-conditions as described in the issue #17.
Release notes
---------------
- The creation/update of Interfaces upon port_stats event now utilizes a locking mechanism to avoid race conditions.

Using switch update_or_create_interface on port_stats event

---

settings.py
tests/unit/test_utils.py
utils.py

Fixes #23 
of_core receives data from Kytos Async TCP server as raw_bytes (possibly aggregated) and transform them into individual OpenFlow messages. As part of this routine, `of_slicer()` is the one responsible for splitting the raw data into individual OpenFlow messages (set of bytes) to be later parsed into OpenFlow objects using python-openflow. of_slicer also takes into consideration that the received bytes can represent incomplete messages (due, for instance, to the socket read buffer), and it will return the list of individual packets and the remaining data. The slicing process does not validated some situations, which can lead to inconsistent messages, infinity loop at the server and memory exhaustion.
This PR will add some sanity checks to the slicing process, to avoid those …

Add sanity checks to of_slicer

---

flow.py

I had to augment how the class was  being instantiated since it was resulting in `TypeError`, it was assuming that the constructor was only taking a single argument, which was true for some actions like `ActionSetQueue`, `ActionSetVlan`, `ActionPushVlan`, and so on, but this premise doesn't hold true for some of the `NoviAction*` classes or any other that takes more args: 
```
cls = <class 'napps.amlight.noviflow.of_core.v0x04.action.NoviActionSetBfdData'>, action_dict = {'action_type': 'set_bfd', 'interval': 5, 'keep_alive_timeout': 15, 'multiplier': 3, ...}
@classmethod
def from_dict(cls, action_dict):
"""Return an action instance from attributes in a dictionary."""
>       action = cls(None)
E       TypeError: __init__() missing 4 required positional arguments: 'my_disc', 'interval', …
```

[Fix] Augmented ActionBase `from_dict` to pass class kwargs

---

main.py

Fixes #34 
- Updated the log error message passing the expected vars accordingly
Example with this fix, when trying to reproduce the original error on #34: 
```
2021-11-26 12:57:51,836 - ERROR [kytos.napps.kytos/of_core] (Thread-175) OFPT_ERROR: type ErrorType.OFPET_BAD_MATCH, error code 7, from switch 00:00:00:00:00:00:00:01, xid 881795134/348f203e
```

[Fix] OFPT_ERROR 'ErrorMsg' object has no attribute 'dpid'

---

main.py
setup.cfg

Fixes #27 that @italovalcy has reported
- We've had some failing assert calls on `listen_to` decorators being these were being tested out directly, and depending on the threadpool queue/scheduler there's no guarantee it'll be immediately or shortly after executed, since we don't expose a `join/result`, the safest route to be deterministic was to extract the `listen_to` handlers in new methods, and test hem out without depending on threading spawn execution times.

[Fix] Fixed failing unit tests

---

main.py
tests/unit/test_main.py

Fixes #38 
- Updated switch `lastseen` right after the underlying `get_switch_or_create(dpid, conn)` call and before sending `kytos/of_core.handshake.completed`, just so the `is_connected()` method works as intended. 
- Updated switch `lastseen`  before sending `kytos/of_core.handshake.completed`, to fix the `is_connected()` method check.

[Fix] Updated switch `lastseen` before sending `kytos/of_core.handshake.completed`

---

main.py
settings.py
tests/unit/test_main.py

Fixes #25 
Fixes #27 
*Note*: This PR was built on top of PR #28 
Added mechanism to prevent race conditions for the variable `connection.remaining_data`. This variable can be updated from two or more different threads handling `kytos/core.openflow.raw.in` KytosEvents. Thus, I've added a threading Lock mechanism per connection which will guarantee only one thread can update at the same time.
Additionally, the `handle_raw_in` method was creating one KytosEvent for each individual multipart OpenFlow message, which could lead to data loss as described in issue #25. To deal with such scenarios, I've changed the way handle_raw_in works for multipart messages: instead of creating one KytosEvent as soon as the message was unpacked, we group them together and emit the Kytos event at the end; …

Refactor handle_raw_in to avoid data loss under high usage scenarios

---

CHANGELOG.rst
kytos.json
main.py
tests/unit/test_main.py

Fixes #20, this addressed the first requirement, the other two ones were broken down to be addressed [on issue 39 on topology](https://github.com/kytos-ng/topology/issues/39):
`[1.7.0] - 2022-01-04`
- Changed ``update_port_status`` on ``OFPPR_DELETE`` to deactivate an interface instead of deleting it to keep the same object reference that ``topology`` uses when managing the status of a link.
- Before shutting down mininet, all interfaces are active from the topology perspective:
```
❯ http http://127.0.0.1:8181/api/kytos/topology/v3/interfaces | jq -r '.interfaces[].active'
true
true
true
true
true
true
true
true
true
true
```
- After shutting down mininet, all interfaces are active from the topology perspective (the only ones UP are `OFPP_LOCAL`):
```
❯ http …
```

[Fix] `update_port_status` on `OFPPR_DELETE` to deactivate an interface

---

.coveragerc
setup.cfg
setup.py

- [Same as `storehouse` PR #6](https://github.com/kytos-ng/storehouse/pull/6), `of_core` didn't have extra runtime dependencies, but with the `install_requires` in place it's normalized now like the other NApps.
- I'll regenerate and upgrade the `requirements/dev.txt` in a next opportunity on issue #43

[Fix] setup.py install_requires dependencies housekeeping

---

CHANGELOG.rst
kytos.json
main.py
tests/unit/test_main.py

This change was fixed and supposed to land on PR #41, however back then it got merged into a branch that had already landed, so it never made to master, so I'm cherry picking the commits again. Having `Automatically delete head branches` enabled, which we do now should prevent this from happening again when there are multiple branches on top of each other. 
[2022.1.1] - 2022-02-03
***********************
- Added ``switch.update_lastseen()`` on handle_features_reply

[Fix] `update_lastseen()` on features reply (PR 41 cherry picked)

---

CHANGELOG.rst
README.rst
tests/unit/v0x04/test_utils.py
v0x04/utils.py

Fixes #52 
- Added new KytosEvent ``kytos/of_core.switch.interfaces.created`` meant for bulk updates or insertions.
I realized this opportunity when I was implementing the DB updates and insertions on topology, so now subscribers who can benefit from it can subscribe accordingly.

Added new `kytos/of_core.switch.interfaces.created` event

---

setup.py

Fix #58 
Running the command `python setup.py egg_info ` returns an error.
This PR intend to fix this issue, adding the parameter `packages=[]` to the setup command.
It must solve dependency issues when running `pip-compile `in other NApps.

fix setup.py egg_info with python 3.9

---

CHANGELOG.rst
flow.py
main.py
tests/unit/test_flow.py
tests/unit/test_main.py
tests/unit/test_match.py
v0x01/flow.py

- Added ``match_id`` attribute on ``Flow`` as a unique match identifier for efficient overlapping matches updates, minimizing extra DB lookups that would be needed otherwise.
- Match OF10 ``as_dict`` to only included explicit set values.
This picture illustrates a `POST /api/kytos/flow_manager/v2/flows/` on `flow_manager` (that's in progress on https://github.com/kytos-ng/flow_manager/issues/75), by leveraging this `match_id` there's a single update, minimizing DB round trips when inserting or updating a flow, minimizing locks and delegating as much to Mongo whenever applicable
I wasn't going to support OF10 either on this attribute, since we have mapped the issues to deprecate it, but since we haven't yet and the fix was simple I committed it. We can drop OF1.0 on issue #50 .

[Feature] Added `Flow` `match_id` attribute for efficient overlapping matches updates

---

CHANGELOG.rst
main.py

Fixes #61 
Now it correctly logs and then publishes the OFPT_ERROR message, I removed the hex f-string format, it was there primarily for convenience.
This branch is on top of #60 to facilitate local development and managing in-flight branches.
- OFPT_ERROR message could crash when logging it.
```
2022-05-19 16:01:02,889 - ERROR [kytos.napps.kytos/of_core] (thread_pool_sb_7) OFPT_ERROR: type ErrorType.OFPET_BAD_MATCH, error code 7, from switch 00:00:00:00:00:00:00:01, xid 130177
2539
2022-05-19 16:01:02,894 - WARNING [kytos.napps.kytos/flow_manager] (thread_pool_sb_7) Deleting flow: {'switch': '00:00:00:00:00:00:00:01', 'table_id': 0, 'match': {'dl_vlan': 10000}, '
priority': 32768, 'idle_timeout': 0, 'hard_timeout': 0, 'cookie': 0, 'id': '502866b8912c0eee9e98345b01013524', 'stats': {}, …
```

[Fix] Handler kytos/core.openflow.raw.in crashed when trying to log an OFPT_ERROR

---

CHANGELOG.rst
tests/unit/test_flow.py
v0x04/flow.py

Fixes #64 
- Fixed inconsistent Flow04 id for empty list actions, now the id is equivalent with the default values for this particular case.

[Fix] Flow04 inconsistent id for empty actions

---

CHANGELOG.rst
msg_prios.py
tests/unit/test_msg_prios.py

- Added msg_prios module to define OpenFlow message priorities used in the core queues and covered with unit tests
Currently, only the `msg_out` queue is making use of priority, see this infrastructure/core PR https://github.com/kytos-ng/kytos/pull/226. In the future, we'll also have it for `msg_in`, and then we'll keep defining the rest of the OpenFlow message priorities that are primarily used as needed. NApps that put OpenFlow messages (`flow_manager`, `of_lldp`, `sdntrace`, and so on) are supposed to import and use this `msg_prios` module to get the message priority.

[Feature] Added OpenFlow msg_prios module for core queues priorities

---

main.py
tests/unit/test_main.py

Fixes #72 
- Extracted request_flow_list for testability
[This call here](https://github.com/kytos-ng/of_core/blob/fix/issue_72/main.py#L202) was also spawning an extra thread since it's already being called from a `listen_to` handler.  In the future, we might introduce more `async` methods and tasks, for now it's probably not worth on this part considering the efforts on refactoring tests too.

[Fix] Extracted request_flow_list for testability

---

CHANGELOG.rst
kytos.json
main.py

- Bumped 2022.2.0
- Reverted temporary `logging.getLogger` since this PR https://github.com/kytos-ng/kytos/pull/257 has landed

[Release] Bumped 2022.2.0

---

README.rst

I found two events that were not listed in the readme: 
kytos/of_core.port_stats
kytos/of_core.handshake.completed
A comment regarding the 'kytos/of_core.switch.interface.created' and 'kytos/of_core.switch.interfaces.created' events. Why are they not treated as a single event? The first one is a particular case of the second one, where the list of interfaces is made up of a single element, right?

Another readme update

---

CHANGELOG.rst
kytos.json
main.py

Fixes #79 
- Made a shallow copy when iterating on switches to avoid RuntimeError dictionary changed
- Bumped 2022.2.1 (first patch of this version for this NApp)
- Updated changelog

[Release][Fix] Made a shallow copy when iterating on switches to avoid RuntimeError dictionary changed

---

main.py
requirements/dev.txt
setup.cfg
setup.py
tests/conftest.py
tests/helpers.py
tests/integration/test_main.py
tests/unit/test_main.py
tests/unit/test_utils.py
tests/unit/v0x01/test_utils.py
tests/unit/v0x04/test_utils.py
utils.py
v0x01/utils.py

- Ugraded core dev dependencies (they needed to be regenerated). It's related to https://github.com/kytos-ng/kytos/pull/284. 
- I've also upgraded `pylint` and fixed linter errors that showed up. 
- For now, `feature/upgrade_dependencies` kytos branch is pinned just so tests pass in the CI. I'll revert this after before this PR gets merged after review.

Upgrade core development dependencies

---

README.rst
main.py
setup.py
tests/integration/test_flow.py
tests/integration/test_main.py
tests/integration/test_match.py
tests/unit/test_flow.py

Issue: #68 
Progress on updating integration test.
`test_execute()` is still hanging. `napp.controller.buffers.msg_out.get()` has no events and hangs.
`test_handle_multipart_reply()` fails. `napp._multipart_replies_xids` is not being populated at all.
`test_handle_port_desc_multipart_reply()` has more events. Code change for `_handle_multipart_reply()` from:
```
stats_event = KytosEvent(name=event_name,
content={'source': switch.connection,
'message': port_desc})
napp.handle_multipart_reply(stats_event)
```
To:
```
stats_event = KytosEvent(name=event_name,
content={'source': switch.connection,
'message': port_desc})
reply = stats_event.content['message']
event_switch = stats_event.source.switch
await napp._handle_multipart_reply(reply, event_switch)
```
Produces more events:
``` …
```

Integration test update

---

CHANGELOG.rst
tests/unit/test_action.py
v0x04/flow.py

Fixes #87 
- Augmented ``InstructionAction.from_of_instruction`` to support deserializing ActionExperimenter from ``FlowStats`` entries.
NApps who register `ActionExperimenter` experimenter classes are supposed to also register the deserialization accordingly.
I'll post the local tests on https://github.com/kytos-ng/flow_stats/issues/43

[Fix] Support ActionExperimenter sub classes to be deserialized from bytes

---

CHANGELOG.rst
main.py
tests/unit/test_main.py

Closes #91 
- See updated changelog file
- I ended up using async handlers to avoid preemption and keep it lightweight (and aligned with other handlers)
I explored locally simulating both events, and I temporarily added a log entry (`popping multipart replies for ...`):
- Switch reconnecting, once the connection was lost, it popped the multipart replies accordingly:
```
kytos $> 2022-12-08 12:31:01,552 - INFO [kytos.core.atcp_server] (MainThread) Connection lost with client 127.0.0.1:57834. Reason: Request closed by client
2022-12-08 12:31:01,553 - INFO [kytos.napps.kytos/of_core] (MainThread) popping multipart replies for Switch('00:00:00:00:00:00:00:01')
2022-12-08 12:31:03,077 - INFO [kytos.core.atcp_server] (MainThread) New connection from 127.0.0.1:35414
2022-12-08 12:31:03,406 - …
```

[Fix] Reset multipart replies on connection lost and OF connection errors

---

CHANGELOG.rst
main.py
tests/unit/test_main.py
tests/unit/v0x04/test_utils.py
v0x04/utils.py

Fix #89 
- ``OFPPS_LIVE`` is now considered when handling port description and port status
I've explored it with OvS and NoviFlow switches at AmLight to make sure that ``OFPPS_LIVE`` on NoviFlow OpenFlow implementation would also behave correctly:
```
port admin link description       port admin link description
---- ----- ---- -------------     ---- ----- ---- -------------
1    up    up   Novi05-1          19   up    up   loop-20
2    up    up   Novi02-2          20   up    up   loop-19
3    down  down                   21   up    down
4    down  down                   22   up    down
5    up    down                   23   up    up   INT01-enp33s0
6    up    down                   24   up    down
7    up    down                   25   up    down
8    up    down                   26   up …
```

[Fix] `OFPPS_LIVE` is now considered when handling port description and port status

---

CHANGELOG.rst
main.py

Fixes #7 
This PR improves the logging message sent upon receiving a PortStatus OF message to help the network operator understand the network's state from the log messages (very useful for troubleshooting activities).
Before this PR, the only message that was being recorded at the logs were `Modified {interface} {dpid}:{port_number}`: no info about the new state and no info when other states were being recorded.
Running Kytos with this PR and simulating a link failure and recovery gives the following log messages:
```
Jan 12 17:57:41 4919fb6963ef kytos.napps.kytos/of_core:INFO main:652:  PortStatus modified interface 00:00:00:00:00:00:00:12:1 state 0
Jan 12 17:57:41 4919fb6963ef kytos.napps.kytos/of_core:INFO main:652:  PortStatus modified interface 00:00:00:00:00:00:00:12:1 state …
```

Improve log message for PortStatus events

---

CHANGELOG.rst
kytos.json
tests/unit/test_action.py
v0x04/flow.py

Closes #103 
See updated changelog file. 
This bug was a result of me using a older version of `pyof` when I fixed issue #87 on PR https://github.com/kytos-ng/of_core/pull/88, it fixed the original issue, but then I also relied on an old removed `body` value from `ActionExperimenter.body` which introduced this issue here. Since the classes are being registered correctly by `noviflow` NApp then `from_of_action` should work as it used to.
- Installed both `push_int` and `pop_int` experimenter actions on a NoviFlow switch
```
kytos $> 2023-02-22 18:57:49,762 - INFO [kytos.napps.kytos/flow_manager] (Thread-92) Send FlowMod from request dpid: 00:00:00:00:00:00:00:01, command: add, force: False, flows_dict: {'flows': [{'priority': 100, 'match': {'in_port': 1}, 'actions': [{'action_type': …
```

fix: release 2022.3.1: experimenter class deser shouldn't use old `pyof ActionExperimenter.body`

---

CHANGELOG.rst
tests/integration/v0x04/test_match.py
v0x04/match_fields.py

Related to mef_eline PR [#258](https://github.com/kytos-ng/mef_eline/pull/258)
From `MatchDLVLAN.as_of_tlv()`, `self.value` now can be non-existent `VlanId.OFPVID_NONE`
From `MatchDLVLAN.from_of_tlv()`, `tlv.oxm_value` now can handle the `any` case with `oxm_value = '4096/4096'`
Installing this EVC through `mef_eline` api:
```
{
"name": "my evc1",
"dynamic_backup_path": true,
"enabled": true,
"uni_a": {
"tag": {"tag_type": 1, "value": "any"},
"interface_id": "00:00:00:00:00:00:00:01:1"
},
"uni_z": {
"tag": {"tag_type": 1, "value": "untagged"},
"interface_id": "00:00:00:00:00:00:00:02:1"
}
}
```
Does not trigger consistency check loop (alien, delete, missing, install) with different values for the UNI tags. Confirming that the de-serialization is working as desired.

Added a way to handle `4096/4096` and 0

---

CHANGELOG.rst
main.py
tests/unit/test_main.py

Closes #110 
See updated changelog file
Rerun `kytosd` again with this branch:
```
kytos $> 2023-04-11 18:00:42,727 - INFO [kytos.core.atcp_server] (MainThread) New connection from 127.0.0.1:48032                                                                         
2023-04-11 18:00:42,728 - INFO [kytos.core.atcp_server] (MainThread) New connection from 127.0.0.1:48038
2023-04-11 18:00:42,732 - INFO [kytos.core.atcp_server] (MainThread) New connection from 127.0.0.1:48050
2023-04-11 18:00:43,263 - INFO [kytos.napps.kytos/of_core] (thread_pool_sb_0) Connection ('127.0.0.1', 48032), Switch 00:00:00:00:00:00:00:01: OPENFLOW HANDSHAKE COMPLETE
2023-04-11 18:00:43,275 - INFO [kytos.napps.kytos/of_core] (thread_pool_sb_1) Connection ('127.0.0.1', 48038), Switch 00:00:00:00:00:00:00:03: …
```

fix: gracefully handled `kytos/core.openflow.connection.error` when a switch hasn't been created yet

---

CHANGELOG.rst
README.rst
main.py
table.py
tests/integration/test_main.py
tests/unit/test_main.py
tests/unit/test_table.py
v0x04/utils.py

Closes #113 
Add `update_table_list` to start receiving `MultipartType.OFPMP_TABLE`.
Add a new class: TableStats for the data received from `MultipartType.OFPMP_TABLE`
Add `_handle_multipart_table_stats` to get the data and publish a new event: `kytos/of_core.table_stats.received`
I made sure to get messages with table stats by putting a temporary log:
```
2023-05-13 00:11:45,166 - INFO [kytos.napps.kytos/of_core] (MainThread) Table stats received: 254 tables
```
Progress..

feature: Receive table stats

---

CHANGELOG.rst
main.py
tests/unit/test_main.py

Closes #123 (thanks @italovalcy for catching this and your initial analysis)
See updated changelog file
I simulated a few reconnections, it's working as expected:
```
kytos $> 2023-09-19 16:14:29,234 - INFO [kytos.core.atcp_server] (MainThread) Connection lost with client 127.0.0.1:51212. Reason: Request closed by client                              
2023-09-19 16:14:30,736 - INFO [kytos.core.atcp_server] (MainThread) New connection from 127.0.0.1:51352
kytos $>                                                                                                                                                                                 
kytos $> 2023-09-19 16:14:33,127 - INFO [kytos.napps.kytos/of_core] (thread_pool_sb_11) Connection ('127.0.0.1', 51352), Switch 00:00:00:00:00:00:00:01: …
```

fix: multipart replies clean up now happens before connection gets established to be safer

---

tests/integration/test_main.py

Closes #128
Fixed/updated test. Event `kytos/core.switch.new` now is sent by `conn` instead of `app`.
Run tox
N/A

Fixed test

---

CHANGELOG.rst
main.py
tests/unit/test_main.py

Closes #132 
See updated changelog file 
- Simulated a few PortStatus and it behaved as expected
```
kytos $> 2024-03-05 13:08:28,954 - INFO [uvicorn.access] (MainThread) 127.0.0.1:55682 - "GET /api/kytos/topology/v3/ HTTP/1.1" 200                                                       
2024-03-05 13:08:28,959 - INFO [uvicorn.access] (MainThread) 127.0.0.1:55684 - "GET /api/kytos/flow_manager/v2/stored_flows?state=installed&cookie_range=12321848580485677056&cookie_rang
e=12393906174523604991&dpid=00%3A00%3A00%3A00%3A00%3A00%3A00%3A01 HTTP/1.1" 200
2024-03-05 13:08:31,187 - INFO [kytos.napps.kytos/mef_eline] (thread_pool_app_0) Event handle_link_up Link(Interface('s1-eth3', 3, Switch('00:00:00:00:00:00:00:01')), Interface('s2-eth2
', 2, Switch('00:00:00:00:00:00:00:02')), …
```

fix: set interface.speed on PortStatus reason OFPPR_ADD and OFPPR_MODIFY

---

CHANGELOG.rst
flow.py
tests/unit/test_flow.py

Closes #136 
- See updated changelog file
- Migration script will be covered on `flow_manager` https://github.com/kytos-ng/flow_manager/issues/188 
- Explored with an equivalent case, same match but different cookie, in the DB and in the switch and the cookie got updated accordingly without duplicating a flow document in the DB:
```
{
"force": false,
"flows": [
{
"priority": 10,
"cookie": 100,
"match": {
"in_port": 1
},
"actions": [
{
"action_type": "output",
"port": 2
}
]
},
{
"priority": 10,
"cookie": 101,
"match": {
"in_port": 1
},
"actions": [
{
"action_type": "output",
"port": 2
}
]
}
]
}
```
```
rs0 [direct: primary] napps> db.flows.find({ "flow.cookie": Decimal128("100") })
rs0 [direct: primary] napps> db.flows.find({ "flow.cookie": Decimal128("101") })
[
{
_id: …
```

fix: `cookie` is no longer a factor of a Flow `match_id`

---

CHANGELOG.rst
kytos.json
main.py
settings.py
tests/unit/test_main.py
tests/unit/v0x04/test_utils.py
v0x04/utils.py

Closes #145 
- See updated changelog file 
- I didn't refactor `update_port_status` to use `switch.update_or_create_interface` since the underlying `threading.Lock` isn't compatible from an asyncio context, and that part isn't the one causing an issue. It was observed with a pcap that indeed there was a 4 ms difference where the port status arrived later, but then our late multipart reply assembled executed last, so now with the local counters it's supposed to be skipped. 
- I added a `settings.SKIP_INTF_STATE_LATE_UPDATES` feature flag for controlled and internal use, eventually this flag will be removed and will always be enabled, it can be handy to have this for now. 
- Release 2025.1.1 is directly targeting `master` since nothing else has landed since the last release
- Explored links …

[release 2025.1.1] fix: skip unordered late assembled MULTIPART_REPLY and PORT_STATUS

---

CHANGELOG.rst
kytos.json
main.py
settings.py
tests/unit/test_main.py
tests/unit/v0x04/test_utils.py
v0x04/utils.py

Closes #145 
- See updated changelog file 
- Backporting PR #146 to 2024.1
- Ran it with 2024.1 NApps:
```
❯ kytos napps list
WARNING kytos (2024.1.5) and kytos utils (2025.1.0) versions are not equal.
Status |           NApp ID            |                                                                Description                                                                
=======+==============================+===========================================================================================================================================
[ie]  | amlight/sdntrace_cp:2024.1.0 | Run tracepaths on OpenFlow in the Control Plane                                                                                           
[ie]  | kytos/flow_manager:2024.1.5  | Manage switches' flows …
```

[release 2024.1.1] fix: skip unordered late assembled MULTIPART_REPLY and PORT_STATUS
